package ua.com.hiringservice.util.mapper.task;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import ua.com.hiringservice.config.MapperConfig;
import ua.com.hiringservice.model.dto.task.PracticalTaskAnswerDto;
import ua.com.hiringservice.model.dto.task.ProvidePracticalTaskAnswerDto;
import ua.com.hiringservice.model.entity.task.PracticalTaskAnswer;

/**
 * Mapper interface for converting between {@link PracticalTaskAnswer} entities and {@link
 * ProvidePracticalTaskAnswerDto} DTOs. Uses {@link MapperConfig} for configuration.
 *
 * <p>The methods defined in this interface provide mapping between entity and DTO representations
 * of {@link PracticalTaskAnswer} instances. Implementation is generated by MapStruct during the
 * build process.
 */
@Mapper(
    uses = {},
    config = MapperConfig.class)
public interface PracticalTaskAnswerMapper {

  @Mapping(target = "taskPassing", ignore = true)
  @Mapping(target = "maxScore", ignore = true)
  @Mapping(target = "id", ignore = true)
  void updateEntityFromDto(
      @MappingTarget PracticalTaskAnswer entity, ProvidePracticalTaskAnswerDto requestDto);

  ProvidePracticalTaskAnswerDto toDto(PracticalTaskAnswer entity);

  @Mapping(target = "taskPassing", ignore = true)
  @Mapping(target = "maxScore", ignore = true)
  PracticalTaskAnswerDto toFullDtoShort(PracticalTaskAnswer practicalTaskAnswer);
}
