package ua.com.hiringservice.util.mapper.task;

import org.mapstruct.Mapper;
import ua.com.hiringservice.config.MapperConfig;
import ua.com.hiringservice.model.dto.task.PracticalTaskImageDto;
import ua.com.hiringservice.model.entity.task.PracticalTaskImage;

/**
 * Mapper interface for converting between {@link PracticalTaskImage} entities and {@link
 * PracticalTaskImageDto} DTOs. Uses {@link MapperConfig} for configuration.
 *
 * <p>The methods defined in this interface provide mapping between entity and DTO representations
 * of {@link PracticalTaskImage} instances. Implementation is generated by MapStruct during the
 * build process.
 *
 * @author Oleksandr Prokopenko
 * @since 2024-03-17
 */
@Mapper(config = MapperConfig.class)
public interface PracticalTaskImageMapper {

  PracticalTaskImageDto toDto(PracticalTaskImage entity);

  PracticalTaskImage toEntity(PracticalTaskImageDto dto);
}
