package ua.com.hiringservice.util.mapper.task;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import ua.com.hiringservice.config.MapperConfig;
import ua.com.hiringservice.model.dto.task.QuestionDto;
import ua.com.hiringservice.model.dto.task.TaskQuestionDto;
import ua.com.hiringservice.model.entity.task.TaskQuestion;

/**
 * Mapper interface for converting between {@link TaskQuestion} entities and {@link TaskQuestionDto}
 * DTOs. Uses {@link MapperConfig} for configuration.
 *
 * <p>The methods defined in this interface provide mapping between entity and DTO representations
 * of {@link TaskQuestion} instances. Implementation is generated by MapStruct during the build
 * process.
 *
 * @see MapperConfig
 */
@Mapper(uses = QuestionDto.class, config = MapperConfig.class)
public interface TaskQuestionMapper {

  @Mapping(target = "question", source = "questionDto")
  TaskQuestion toEntity(TaskQuestionDto taskQuestionDto);

  @Mapping(target = "questionDto", source = "question")
  TaskQuestionDto toDto(TaskQuestion taskQuestion);

  @Mapping(target = "question", source = "questionDto")
  void updateEntityFromDto(
      @MappingTarget TaskQuestion taskQuestion, TaskQuestionDto taskQuestionDto);
}
