INSERT INTO specializations (name)
VALUES ('JavaScript/Front-End'),
       ('Fullstack'),
       ('React Native'),
       ('Java'),
       ('C#/.NET'),
       ('Python'),
       ('PHP'),
       ('Node.js'),
       ('iOS'),
       ('Android'),
       ('C/C++/Embedded'),
       ('Flutter'),
       ('Golang'),
       ('Ruby'),
       ('Scala'),
       ('Salesforce'),
       ('Rust'),
       ('ERP'),
       ('QA Manual'),
       ('QA Automation'),
       ('Design/UI/UX'),
       ('2D/3D Artist/Illustrator'),
       ('Project Manager'),
       ('Product Manager'),
       ('Architect/CTO'),
       ('DevOps'),
       ('Business Analyst'),
       ('Data Science'),
       ('Data Analyst'),
       ('Sysadmin'),
       ('Gamedev/Unity'),
       ('SQL/DBA'),
       ('Security'),
       ('Data Engineer'),
       ('Scrum Master/Agile Coach'),
       ('Marketing'),
       ('HR'),
       ('Recruiter'),
       ('Customer/Technical Support'),
       ('Sales'),
       ('SEO'),
       ('Technical Writing'),
       ('Lead Generation'),
       ('Head/Chief');
